import type { NextPage, GetServerSideProps } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import Avatar from '../components/Avatar'
import { base64Prefix } from '../components/Avatar/constants'
import AvatarModel from '../lib/models/avatar'

type SSRProps = {
  avatars: AvatarModel[]
}

const Home: NextPage<SSRProps> = (props) => {
  const [avatarsList, setAvatarsList] = useState<AvatarModel[]>(props.avatars)

  useEffect(() => {
    setAvatarsList(props.avatars)
  }, [props.avatars])

  const deleteAvatar = (_id: string) => async () => {
      const response = await fetch('/api/avatars', {
        method: 'DELETE',
        body: _id,
      })

      if (response.status === 200) {
        setAvatarsList(avatarsList.filter(a => a._id !== _id))
      }
  }

  return (
    <div className="flex justify-items-center justify-center p-10">
      <Head>
        <title>Avatars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {
          avatarsList.length === 0 
          ? `... Looks like you don't have any avatars, try to upload some`
          : (
            <div className="inline-grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
              {avatarsList.map((a: AvatarModel) => (
                  <Avatar
                    key={a._id}
                    image={base64Prefix + a.image}
                    name={a.name}
                    onClick={deleteAvatar(a._id!)}
                    hoverEnabled
                  />
                )
              )}
            </div>
          )
        }
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const isDev = process.env.NODE_ENV !== 'production'
  const { DEV_URL, PROD_URL } = process.env
  const response = await fetch(`${isDev ? DEV_URL : PROD_URL}/api/avatars`, {
      method: 'GET',
  })

  const data = await response.json()

  return {
    props: {
        avatars: data.message,
    },
  }
}

export default Home
