import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Avatar from '../components/Avatar'
import { base64Prefix } from '../components/Avatar/constants'
import AvatarModel from '../lib/models/avatar'

type SSRProps = {
  avatars: AvatarModel[]
}

const Home: NextPage<SSRProps> = ({ avatars }) => {
  return (
    <div className="flex justify-items-center justify-center p-10">
      <Head>
        <title>Avatars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="inline-grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
        {
          avatars.map((a: AvatarModel) => (<Avatar key={a._id as string} image={base64Prefix + a.image} name={a.name} />))
        }
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const isDev = process.env.NODE_ENV !== 'production';
  let { DEV_URL, PROD_URL } = process.env;
  const response = await fetch(`${isDev ? DEV_URL : PROD_URL}/api/avatars`, {
      method: 'GET',
  });
  let data = await response.json();

  return {
    props: {
        avatars: data.message,
    },
  };
}

export default Home
